#-----------------------------------------------------------
#-- Automatically generated by Reddiag --
#-- Veloce Prototyping System version: 2022.12
#-- Veloce Prototyping System build: 5461546
#-- Time: Thu Dec  7 19:42:12 2023
#-----------------------------------------------------------


# Global comparison nets
#NET TOP.COMPARE_OK_MB1_FA1
#NET TOP.COMPARE_OK_MB1_FA2
#NET TOP.COMPARE_OK_MB1_FB1
#NET TOP.COMPARE_OK_MB1_FB2
#NET TOP.COMPARE_OK_N_MB1_FA1
#NET TOP.COMPARE_OK_N_MB1_FA2
#NET TOP.COMPARE_OK_N_MB1_FB1
#NET TOP.COMPARE_OK_N_MB1_FB2
#NET TOP.TESTING_MB1_FA1
#NET TOP.TESTING_MB1_FA2
#NET TOP.TESTING_MB1_FB1
#NET TOP.TESTING_MB1_FB2
#NET TOP.TESTING_N_MB1_FA1
#NET TOP.TESTING_N_MB1_FA2
#NET TOP.TESTING_N_MB1_FB1
#NET TOP.TESTING_N_MB1_FB2
#
## Internal comparison nets
#NET TOP.fpga_out_MB1_FA1.COMPARE_OK_IN[350:0]
#NET TOP.fpga_out_MB1_FA2.COMPARE_OK_IN[467:0]
#NET TOP.fpga_out_MB1_FB1.COMPARE_OK_IN[428:0]
#NET TOP.fpga_out_MB1_FB2.COMPARE_OK_IN[389:0]
NET tb.counter_a
NET tb.counter_b
NET tb.dut_apb_presetn
NET tb.dut_axi_aresetn
# INTRA_ENABLE nets
