#-----------------------------------------------------------
#-- Automatically generated by Reddiag --
#-- Veloce Prototyping System version: 2022.12
#-- Veloce Prototyping System build: 5461546
#-- Time: Thu Dec  7 19:42:13 2023
#-----------------------------------------------------------


dont_use_empty_fpga
dont_route_aggregator
disable_explore_mode
set_muxable_signal_types -async_data true
set_mux_ratio -from CLOCK -to CLOCK -type RED_DAF8M 30
#DUT wiresets
source wiresets.tcl
use_all_fpgas_in_debug_infrastructure -debug_loop false -trigger_tree false
