#-----------------------------------------------------------
#-- Automatically generated by Reddiag --
#-- Veloce Prototyping System version: 2022.12
#-- Veloce Prototyping System build: 5461546
#-- Time: Thu Dec  7 19:42:13 2023
#-----------------------------------------------------------
#add_backend_constraint_files -file {./new.xdc} -fpga {MB1_FB2} -task pnr -synth vivado -type read_xdc
#add_vivado_command_files -task pnr-phase pre-opt -file ./user_vivado_commands.tcl -fpga MB1_FA1
set_rcm_group_master_clock_frequency -group clk_a -freq 300 -force_unaligned true
set_rcm_group_master_clock_frequency -group clk_b -freq 300 -force_unaligned true
set_message_severity suppress -ids 45103


